import imaplib
import email
from email.header import decode_header
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import time
import os
import markdown
from google import genai

# --- Configuration ---
EMAIL_USER = "metaknews@gmail.com"
EMAIL_PASS = os.getenv("GMAIL_APP_PASSWORD", "your-16-char-app-password")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "your-gemini-api-key")
ALLOWED_SENDERS = ["your-personal-email@gmail.com"]  # Security whitelist

IMAP_SERVER = "imap.gmail.com"
SMTP_SERVER = "smtp.gmail.com"

# Initialize Gemini Client
client = genai.Client(api_key=GEMINI_API_KEY)

SYSTEM_PROMPT = """
You are MetaKNews, an intelligent, analytical email agent and research partner.
You interact exclusively via email. Your replies should feel like high-caliber, 
thoughtful executive memos, editorial briefs, or deep-dive analyses.

Guidelines:
1. Always open with a polite, professional salutation and end with a distinctive sign-off.
2. Structure your response with clear headers, bullet points, and callout sections.
3. Be rigorous, synthesized, and actionable. Avoid robotic conversational filler.
"""

def clean_subject(header_val):
    if not header_val:
        return "No Subject"
    decoded, encoding = decode_header(header_val)[0]
    if isinstance(decoded, bytes):
        return decoded.decode(encoding or "utf-8", errors="ignore")
    return str(decoded)

def get_email_body(msg):
    body = ""
    if msg.is_multipart():
        for part in msg.walk():
            ctype = part.get_content_type()
            cdispo = str(part.get("Content-Disposition"))
            if ctype == "text/plain" and "attachment" not in cdispo:
                payload = part.get_payload(decode=True)
                if payload:
                    body += payload.decode(errors="ignore")
    else:
        payload = msg.get_payload(decode=True)
        if payload:
            body = payload.decode(errors="ignore")
    return body.strip()

def generate_agent_response(subject, body, sender):
    user_prompt = f"Subject: {subject}\nSender: {sender}\n\nMessage Body:\n{body}"
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=[user_prompt],
        config={"system_instruction": SYSTEM_PROMPT}
    )
    return response.text

def send_reply(to_email, original_subject, body_markdown, original_msg_id):
    reply_subject = original_subject if original_subject.lower().startswith("re:") else f"Re: {original_subject}"
    
    # Render styled HTML
    html_content = markdown.markdown(body_markdown, extensions=['extra', 'tables'])
    styled_html = f"""
    <html>
      <head>
        <style>
          body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #222; max-width: 680px; margin: 0 auto; padding: 20px; }}
          h1, h2, h3 {{ color: #111; margin-top: 1.5em; }}
          blockquote {{ border-left: 4px solid #4f46e5; margin: 1.5em 0; padding: 0.5em 1em; background: #f8fafc; color: #475569; }}
          code {{ background: #f1f5f9; padding: 2px 5px; border-radius: 4px; font-size: 0.9em; }}
          hr {{ border: none; border-top: 1px solid #e2e8f0; margin: 2em 0; }}
        </style>
      </head>
      <body>
        {html_content}
        <hr/>
        <p style="font-size: 0.8em; color: #94a3b8;">Generated by MetaKNews Agent</p>
      </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["From"] = f"MetaKNews Agent <{EMAIL_USER}>"
    msg["To"] = to_email
    msg["Subject"] = reply_subject
    if original_msg_id:
        msg["In-Reply-To"] = original_msg_id
        msg["References"] = original_msg_id

    msg.attach(MIMEText(body_markdown, "plain"))
    msg.attach(MIMEText(styled_html, "html"))

    with smtplib.SMTP_SSL(SMTP_SERVER, 465) as server:
        server.login(EMAIL_USER, EMAIL_PASS)
        server.sendmail(EMAIL_USER, [to_email], msg.as_string())

def poll_inbox():
    mail = imaplib.IMAP4_SSL(IMAP_SERVER)
    mail.login(EMAIL_USER, EMAIL_PASS)
    mail.select("inbox")

    status, messages = mail.search(None, 'UNSEEN')
    if status != "OK" or not messages[0]:
        mail.close()
        mail.logout()
        return

    for num in messages[0].split():
        status, data = mail.fetch(num, "(RFC822)")
        if status != "OK":
            continue

        raw_email = data[0][1]
        msg = email.message_from_bytes(raw_email)

        sender = email.utils.parseaddr(msg.get("From"))[1]
        subject = clean_subject(msg.get("Subject"))
        msg_id = msg.get("Message-ID")

        print(f"📩 New email from {sender}: '{subject}'")

        # Sender check
        if ALLOWED_SENDERS and sender not in ALLOWED_SENDERS:
            print(f"⚠️ Skipping email from unauthorized sender: {sender}")
            continue

        body = get_email_body(msg)
        print("🧠 Thinking & generating response...")
        reply_md = generate_agent_response(subject, body, sender)

        print(f"✉️ Sending reply to {sender}...")
        send_reply(sender, subject, reply_md, msg_id)

    mail.close()
    mail.logout()

if __name__ == "__main__":
    print("🚀 MetaKNews Email Agent started. Polling inbox...")
    while True:
        try:
            poll_inbox()
        except Exception as e:
            print(f"Error in poll loop: {e}")
        time.sleep(15)  # Poll every 15 seconds
